# Generated by Django 2.2.3 on 2019-08-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
