# Generated by Django 2.2.5 on 2019-09-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_chatmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrating',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
    ]
