# Generated by Django 2.2.5 on 2019-09-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_clientrating_isbanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerrating',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
    ]
