# Generated by Django 2.2.5 on 2019-09-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20190914_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourrequest',
            name='isBanned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
    ]
