# Generated by Django 2.2.5 on 2019-09-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20190915_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourrequest',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
    ]
