# Generated by Django 2.2.5 on 2019-09-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20190915_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourrequest',
            name='banning',
            field=models.OneToOneField(blank=True, null=True, on_delete=True, to='portal.Banning'),
        ),
    ]
