# Generated by Django 2.2.5 on 2019-09-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20190915_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrating',
            name='banning',
            field=models.OneToOneField(blank=True, null=True, on_delete=True, to='portal.Banning'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='banning',
            field=models.OneToOneField(blank=True, null=True, on_delete=True, to='portal.Banning'),
        ),
        migrations.AlterField(
            model_name='workerrating',
            name='banning',
            field=models.OneToOneField(blank=True, null=True, on_delete=True, to='portal.Banning'),
        ),
    ]
