# Generated by Django 2.2.5 on 2020-04-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20200409_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourrequest',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
