# Generated by Django 2.2.5 on 2020-04-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20200409_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourrequest',
            name='title',
            field=models.TextField(default='labour title by default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\carlo\\PycharmProjects\\project_tfg\\static/media\\static/profile'),
        ),
    ]
