# Generated by Django 2.2.5 on 2020-04-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20200421_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='C:\\Users\\carlo\\PycharmProjects\\project_tfg\\static/media\\static/labour_images')),
            ],
        ),
        migrations.AddField(
            model_name='labourrequest',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='portal.LabourImage'),
        ),
    ]
