# Generated by Django 2.2.5 on 2020-04-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20200421_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labourrequest',
            name='image',
        ),
        migrations.AddField(
            model_name='labourimage',
            name='labour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='labour', to='portal.LabourRequest'),
            preserve_default=False,
        ),
    ]
