# Generated by Django 2.2.5 on 2020-04-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20200421_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='labourrequest',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=True, to='portal.LabourOffer'),
        ),
    ]
